[package]
name = "hdrhistogramr"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "hdrhistogramr"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
hdrhistogram = "7.5.1"
